# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'rbconfig'

VAGRANTFILE_API_VERSION = '2'
ROLE_NAME = 'el7'
HOST_NAME = 'test' + ROLE_NAME

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos71-nocm'
  config.vm.box_url = 'https://tinfbo2.hogent.be/pub/vm/centos71-nocm-1.0.16.box'
  config.vm.define HOST_NAME do |node|
    node.vm.network :private_network, type: 'dhcp'
    node.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'test_full.yml'
    end
  end
end

